# Generated by Django 3.0 on 2020-06-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flori', '0002_auto_20200622_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='pret_cumparare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produse',
            name='tip',
            field=models.CharField(choices=[('Floare', 'Floare'), ('Buchet', 'Buchet'), ('Ghiveci', 'Ghiveci')], default='Floare', max_length=9),
        ),
    ]
