# Generated by Django 3.0 on 2020-06-29 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flori', '0004_auto_20200629_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('poza', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='poze_useri/')),
                ('adresa', models.TextField()),
                ('telefon', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret_achizitie', models.FloatField()),
                ('numar', models.PositiveSmallIntegerField(default=1)),
                ('data', models.DateField(auto_now_add=True)),
                ('finalizat', models.BooleanField(default=False)),
                ('produs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flori.Produse')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flori.Useri')),
            ],
        ),
    ]
