# Generated by Django 3.0 on 2020-07-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flori', '0005_comanda_useri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poze_useri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poza', models.ImageField(blank=True, default='poze/avatar.png', null=True, upload_to='poze/')),
                ('useri_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flori.Useri')),
            ],
        ),
    ]
