# Generated by Django 3.0 on 2020-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flori', '0006_poze_useri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useri',
            name='poza',
            field=models.ImageField(blank=True, default='poze/avatar.png', null=True, upload_to='poze/'),
        ),
        migrations.DeleteModel(
            name='Poze_useri',
        ),
    ]
